user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

tech:
    resource: "@TechBundle/Resources/config/routing.yml"
    prefix:   /tech

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"